import { act, fireEvent, render, screen, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import example from '@/public/interactive-class-example.json';
import { parseInteractiveMaterial } from '@/lib/interactive-material';
import { SimulationRoom } from './SimulationRoom';
import { ContentWindow } from './ContentWindow';
import { LiveRoomView } from './LiveRoomView';
import { createSimulation, joinSimulation, SIMULATION_CODE, simulationCommand, simulationTeacherState, simulationStudentState } from '@/lib/interactive-simulation';

afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });

function mockPopup() {
  const iframe = document.createElement('iframe');
  document.body.appendChild(iframe);
  const popup = iframe.contentWindow!;
  const focus = vi.spyOn(popup, 'focus').mockImplementation(() => {});
  const close = vi.spyOn(popup, 'close').mockImplementation(() => {});
  const open = vi.spyOn(window, 'open').mockReturnValue(popup);
  return { iframe, popup, focus, close, open };
}

describe('contenido en ventana secundaria', () => {
  it('sincroniza el guion privado en su ventana, independiente de resultados y proyección', async () => {
    const notes = mockPopup();
    const projection = mockPopup();
    vi.mocked(window.open).mockReturnValueOnce(notes.popup).mockReturnValueOnce(projection.popup);
    const user = userEvent.setup();
    const material = parseInteractiveMaterial(example)!;
    material.screens[0].teacherNotes = 'GUION INICIAL PRIVADO';
    material.screens[1].teacherNotes = 'GUION DE LA PREGUNTA';
    let model = joinSimulation(createSimulation(material, 'Clase con guion'), 'sim-1', SIMULATION_CODE);
    const view = () => <LiveRoomView state={simulationTeacherState(model, material.screens[0].id)} results={material.screens[0].id} setResults={vi.fn()} send={vi.fn()} />;
    const { rerender, unmount } = render(view());
    expect(screen.getByText('GUION INICIAL PRIVADO')).toBeInTheDocument();
    await user.click(screen.getByRole('button', { name: 'Abrir guion en otra ventana' }));
    await user.click(screen.getByRole('button', { name: 'Abrir ventana de proyección' }));
    const script = within(notes.popup.document.body);
    const projected = within(projection.popup.document.body);
    expect(notes.popup.document.title).toBe('Clase con guion · Guion docente');
    expect(script.getByText('GUION INICIAL PRIVADO')).toBeInTheDocument();
    expect(projected.queryByText(/GUION/)).not.toBeInTheDocument();
    model = simulationCommand(model, 'teacher', { kind: 'screen', index: 1, revision: model.session.revision });
    rerender(view());
    expect(script.queryByText('GUION INICIAL PRIVADO')).not.toBeInTheDocument();
    expect(script.getByText('GUION DE LA PREGUNTA')).toBeInTheDocument();
    expect(script.getByText('Pantalla 2 de 4')).toBeInTheDocument();
    expect(projected.queryByText(/GUION/)).not.toBeInTheDocument();
    model = simulationCommand(model, 'teacher', { kind: 'screen', index: 2, revision: model.session.revision });
    rerender(view());
    expect(script.getByText('Esta pantalla todavía no tiene guion docente.')).toBeInTheDocument();
    rerender(<LiveRoomView state={simulationStudentState(model, 'sim-1')} results="" setResults={vi.fn()} send={vi.fn()} />);
    expect(screen.queryByRole('button', { name: /guion/ })).not.toBeInTheDocument();
    expect(notes.close).toHaveBeenCalled();
    expect(projection.close).toHaveBeenCalled();
    unmount(); notes.iframe.remove(); projection.iframe.remove();
  });
  it('proyecta resultados grupales en vivo y mantiene identidades, textos y soluciones en el panel docente', async () => {
    const { iframe, popup, close } = mockPopup();
    const user = userEvent.setup();
    const material = parseInteractiveMaterial(example)!;
    let model = joinSimulation(createSimulation(material, 'Clase para proyectar'), 'sim-1', SIMULATION_CODE);
    model = { ...model, students: model.students.map((s) => ({ ...s, name: 'Nombre privado del alumno' })) };
    let results = '';
    const send = vi.fn(async () => true);
    const view = () => <LiveRoomView state={simulationTeacherState(model, results)} results={results} setResults={vi.fn()} send={send} />;
    const { rerender, unmount } = render(view());
    await user.click(screen.getByRole('button', { name: 'Abrir ventana de proyección' }));
    const projection = within(popup.document.body);
    expect(popup.document.title).toBe('Clase para proyectar · Proyección');
    expect(projection.getByRole('heading', { name: 'Aprender participando' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Siguiente pantalla' })).toBeInTheDocument();
    const move = (index: number) => { model = simulationCommand(model, 'teacher', { kind: 'screen', index, revision: model.session.revision }); };
    const open = () => { model = simulationCommand(model, 'teacher', { kind: 'activity', open: true, revision: model.session.revision }); };
    move(1); rerender(view());
    expect(projection.getByText('Buscar evidencias y contrastarlas')).toBeInTheDocument();
    expect(projection.getByText('Esperá a que el docente abra la actividad.')).toBeInTheDocument();
    open();
    rerender(view());
    expect(projection.getByText('0 de 1 participantes respondieron.')).toBeInTheDocument();
    expect(projection.getAllByText('0 respuestas · 0 %')).toHaveLength(3);
    model = simulationCommand(model, { studentId: 'sim-1' }, { kind: 'answer', screenId: model.session.screenId, revision: model.session.revision, answer: 'a' });
    rerender(view());
    expect(projection.getByText('Actividad abierta. Respondé desde tu dispositivo.')).toBeInTheDocument();
    expect(screen.getByText(/Opción prevista/)).toBeInTheDocument();
    expect(screen.getByText(/1 de 1 participantes respondieron/)).toBeInTheDocument();
    expect(projection.getByText('1 respuesta · 100 %')).toBeInTheDocument();
    model = joinSimulation(model, 'sim-2', SIMULATION_CODE);
    model = simulationCommand(model, { studentId: 'sim-2' }, { kind: 'answer', screenId: model.session.screenId, revision: model.session.revision, answer: 'b' });
    results = 'encuesta'; rerender(view());
    expect(projection.getByText('2 de 2 participantes respondieron.')).toBeInTheDocument();
    expect(projection.getAllByText('1 respuesta · 50 %')).toHaveLength(2);
    model = simulationCommand(model, 'teacher', { kind: 'activity', open: false, revision: model.session.revision });
    rerender(view());
    expect(projection.getAllByText('1 respuesta · 50 %')).toHaveLength(2);
    for (const text of [/Opción prevista/, /Nombre privado/, /PRUEBA01/, /Respuestas · sólo docentes/]) {
      expect(projection.queryByText(text)).not.toBeInTheDocument();
    }
    expect(projection.queryByRole('button')).not.toBeInTheDocument();
    expect(projection.queryByRole('radio')).not.toBeInTheDocument();
    expect(projection.queryByRole('combobox')).not.toBeInTheDocument();
    move(2); results = 'pregunta'; rerender(view());
    expect(projection.getByRole('heading', { name: '¿Cómo preferís explorar un tema nuevo?' })).toBeInTheDocument();
    expect(screen.getByText(/2 de 2 participantes respondieron/)).toBeInTheDocument();
    expect(projection.queryByRole('region', { name: 'Resultados de la pregunta' })).not.toBeInTheDocument();
    open(); rerender(view());
    expect(projection.getByText('0 de 2 participantes respondieron.')).toBeInTheDocument();
    move(3); open(); results = '';
    model = simulationCommand(model, { studentId: 'sim-1' }, { kind: 'answer', screenId: model.session.screenId, revision: model.session.revision, answer: 'REFLEXIÓN PRIVADA' });
    rerender(view());
    expect(screen.getByText('REFLEXIÓN PRIVADA')).toBeInTheDocument();
    expect(projection.queryByText('REFLEXIÓN PRIVADA')).not.toBeInTheDocument();
    expect(projection.queryByRole('textbox')).not.toBeInTheDocument();
    expect(projection.getByRole('heading', { name: 'Una idea para llevarte' })).toBeInTheDocument();
    model = simulationCommand(model, 'teacher', { kind: 'finish', revision: model.session.revision });
    rerender(view());
    expect(projection.getByText('La sesión finalizó.')).toBeInTheDocument();
    expect(send).not.toHaveBeenCalled();
    unmount(); expect(close).toHaveBeenCalled(); iframe.remove();
  });

  it('explica el bloqueo del navegador y permite reintentar sin perder la clase', async () => {
    vi.spyOn(window, 'open').mockReturnValue(null);
    const user = userEvent.setup();
    render(<ContentWindow title="Clase"><p>Contenido</p></ContentWindow>);
    await user.click(screen.getByRole('button', { name: 'Abrir sólo el contenido en una ventana nueva' }));
    expect(screen.getByRole('alert')).toHaveTextContent('navegador bloqueó');
    expect(screen.getByRole('button', { name: 'Abrir sólo el contenido en una ventana nueva' })).toBeEnabled();
  });

  it('sincroniza pantallas y respuestas desde la ventana del alumno sin mostrar controles ni soluciones docentes', async () => {
    const { iframe, popup, close, open, focus } = mockPopup();
    const fetch = vi.fn(); vi.stubGlobal('fetch', fetch);
    const user = userEvent.setup();
    const { unmount } = render(<SimulationRoom material={parseInteractiveMaterial(example)!} title="Clase de ensayo" />);
    const teacher = within(screen.getByRole('region', { name: 'Vista docente' }));
    const pupil = within(screen.getByRole('region', { name: 'Vista del alumno' }));
    expect(teacher.queryByRole('button', { name: /ventana nueva/ })).not.toBeInTheDocument();
    await user.type(pupil.getByRole('textbox', { name: 'Código de prueba' }), 'PRUEBA01');
    await user.click(pupil.getByRole('button', { name: 'Entrar como alumno' }));
    await user.click(pupil.getByRole('button', { name: 'Abrir sólo el contenido en una ventana nueva' }));
    const content = within(popup.document.body);
    expect(content.getByRole('heading', { name: 'Aprender participando' })).toBeInTheDocument();
    expect(content.getByText('Simulación · alumno ficticio')).toBeInTheDocument();
    expect(content.queryByText('PRUEBA01')).not.toBeInTheDocument();
    expect(content.queryByRole('button', { name: 'Siguiente pantalla' })).not.toBeInTheDocument();
    await user.click(pupil.getByRole('button', { name: 'Volver a la ventana de contenido' }));
    expect(open).toHaveBeenCalledTimes(1);
    expect(focus).toHaveBeenCalledTimes(2);
    await user.click(teacher.getByRole('button', { name: 'Siguiente pantalla' }));
    expect(content.getByRole('radio', { name: 'Buscar evidencias y contrastarlas' })).toBeDisabled();
    expect(content.queryByText(/Opción prevista/)).not.toBeInTheDocument();
    await user.click(teacher.getByRole('button', { name: 'Abrir respuestas' }));
    fireEvent.click(content.getByRole('radio', { name: 'Buscar evidencias y contrastarlas' }));
    await act(async () => { fireEvent.submit(content.getByRole('button', { name: 'Enviar respuesta' }).closest('form')!); });
    expect(teacher.getByText(/1 de 1 participantes respondieron/)).toBeInTheDocument();
    expect(pupil.getByText(/Tu respuesta quedó guardada/)).toBeInTheDocument();
    expect(content.getByText(/Tu respuesta quedó guardada/)).toBeInTheDocument();
    await user.click(teacher.getByRole('button', { name: 'Siguiente pantalla' }));
    expect(content.getByRole('radio', { name: 'Ver ejemplos' })).toBeDisabled();
    expect(content.queryByText(/Tu respuesta quedó guardada/)).not.toBeInTheDocument();
    vi.spyOn(window, 'confirm').mockReturnValue(true);
    await user.click(teacher.getByRole('button', { name: 'Finalizar ensayo' }));
    expect(content.getByText('El ensayo terminó.')).toBeInTheDocument();
    expect(fetch).not.toHaveBeenCalled();
    unmount();
    expect(close).toHaveBeenCalled();
    iframe.remove();
  });

  it('permite volver a abrir tras cerrar la ventana y la cierra al salir de la clase original', async () => {
    const { iframe, popup, open, close } = mockPopup();
    const user = userEvent.setup();
    const { unmount } = render(<ContentWindow title="Clase"><p>Contenido</p></ContentWindow>);
    await user.click(screen.getByRole('button', { name: /ventana nueva/ }));
    act(() => { popup.dispatchEvent(new Event('pagehide')); });
    await user.click(screen.getByRole('button', { name: /ventana nueva/ }));
    expect(open).toHaveBeenCalledTimes(2);
    act(() => { window.dispatchEvent(new Event('pagehide')); });
    expect(close).toHaveBeenCalled();
    unmount(); iframe.remove();
  });
});
